<?php
//
// iTop module definition file
//

SetupWebPage::AddModule(
	__FILE__, // Path to the current file, all other file names are relative to the directory containing this file
	'knowitop-object-template-workorder/1.0.0',
	array(
		// Identification
		//
		'label' => 'Work order object templating module',
		'category' => 'business',

		// Setup
		//
		'dependencies' => array(
			'knowitop-object-template-base/1.0.0',
			'itop-tickets/2.7.0',
		),
		'mandatory' => false,
		'visible' => true,

		// Components
		//
		'datamodel' => array(
			'model.knowitop-object-template-workorder.php', // Contains the PHP code generated by the "compilation" of datamodel.knowitop-object-template-base.xml
		),
		'webservice' => array(

		),
		'data.struct' => array(
			// add your 'structure' definition XML files here,
		),
		'data.sample' => array(
			// add your sample data XML files here,
		),

		// Documentation
		//
		'doc.manual_setup' => '', // hyperlink to manual setup documentation, if any
		'doc.more_information' => '', // hyperlink to more information, if any 

		// Default settings
		//
		'settings' => array(
			// Module specific settings go here, if any
		),
	)
);
